### PR TITLE
Server docker fix

### PR DESCRIPTION
**Pull request by SantoshKumarRavi**
**Changes :**
server docker crashes due to not implementing`  prisma migrate and env `configuration in docker setup

### Working Demo
[screen-capture (13).webm](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/105963429/968ae0a6-c704-4ac0-a6a6-f631d6782e32)

### CODE REVIEW

**Comment by AprilNEA** [comment]
I‘m sorry. I just recover from vacation mode. Why you close this PR?

**Comment by SantoshKumarRavi** [comment]
i am referencing  `prisma Database url ` from .env.
i need to get from config.yaml due to single source of truth file.
i am figuring out that. but not able to find solution.

```
env_file:
      - .env
```
      
after that i will make pr from my official account.

**Comment by SantoshKumarRavi** [comment]
@AprilNEA  i opened 
https://github.com/AprilNEA/ChatGPT-Admin-Web/pull/153

**Comment by AprilNEA** [comment]
> @AprilNEA i opened #153

Thank you very much. I'll take care of it as soon as I can.

**Pull request closed without merging**
